# Generated by Django 6.0.6 on 2026-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '🔴 Pending'), ('COMPLETED', '🟢 Completed')], default='PENDING', max_length=20),
        ),
    ]
