# Generated by Django 6.0.6 on 2026-06-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('TNG', 'TNG e-Wallet')], default='TNG', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed/Paid')], default='PENDING', max_length=20),
        ),
    ]
